<a href="https://colab.research.google.com/github/youness0706/AppsDATA/blob/main/Copy_of_NumPyApps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="text-align:center">
    <img src="attachment:aecdb6fe-95ae-44d9-8cc9-de83ccf69498.png" width="200" alt="Apps Club Logo">
</p>


# NumPy  - Numerical Python

### Importing Numpy

In [ ]:
import numpy as np

### Create NumPy arrays

- 1D array :

In [ ]:
a=np.array([1,2,3,4,5,6])


In [ ]:
np.array([1,8,6,9,7,2])

array([1, 8, 6, 9, 7, 2])

- 2D array:

In [ ]:
b=np.array([[7,56,7,9],[87,8,6,9]])

In [ ]:
a.size

6

### Array Attribute

The attribute <code>size</code> is the number of elements in the array:


The attribute <code>ndim</code> represents the number of array dimensions, or the rank of the array. In this case, one:


In [ ]:
a.ndim

1

The attribute <code>shape</code> is a tuple of integers indicating the size of the array in each dimension:


In [ ]:
a.shape

(6,)

### Slicing

We pass slice like this: [start:end].The element at end index is not being included in the output.

In [ ]:
print(a[0:0])

[]


In [ ]:
print(a[0:2])

[1 2]


In [ ]:
print(b[1:,1:])

[[8 6 9]]


We can also define the steps in slicing, like this: [start:end:step].

In [ ]:
print(a[0:4:2])


[1 3]


If we don't pass start its considered 0 [:end]

In [ ]:
print(a[:2])

[1 2]


If we don't pass end it considers till the length of array.  [start:]

In [ ]:
print(a[1:])

[2 3 4 5 6]


### Accessing different elements of a Numpy Array

We simply use the square brackets and the indices corresponding to the element we would like:

- 1D array : arr[index]

In [ ]:
print(a[1])

2


- 2D array : arr[row, col]

In [ ]:
print(b[0,1])

56


- 2D array : arr[row][col]

In [ ]:
b[1][2]

6

Slicing X Accessing

In [ ]:
print(b[2:][:2])

[]


In [ ]:
print(b[:2][:2])

[[ 7 56  7  9]
 [87  8  6  9]]


In [ ]:
print(b[:1][:2])

[[ 7 56  7  9]]


## Numpy Array Operations

You could use arithmetic operators directly between NumPy arrays

In [ ]:
b*2

array([[ 14, 112,  14,  18],
       [174,  16,  12,  18]])

In [ ]:
b/2

array([[ 3.5, 28. ,  3.5,  4.5],
       [43.5,  4. ,  3. ,  4.5]])

In [ ]:
b*3.14

array([[ 21.98, 175.84,  21.98,  28.26],
       [273.18,  25.12,  18.84,  28.26]])

In [ ]:
b/len(b)

array([[ 3.5, 28. ,  3.5,  4.5],
       [43.5,  4. ,  3. ,  4.5]])

In [ ]:
b+30

array([[ 37,  86,  37,  39],
       [117,  38,  36,  39]])

In [ ]:
b-40

array([[-33,  16, -33, -31],
       [ 47, -32, -34, -31]])

### Numpy Statistical Functions

Create a numpy array

In [ ]:
my_array = np.array([[5, 8, 9, 3,88,99],sorted([5, 8, 9, 3,88,99]),[5, 8, 9, 3,88,99],sorted([5, 8, 9, 3,88,99])])


Get the mean of numpy array

In [ ]:
np.mean(my_array)

35.333333333333336

Get the standard deviation of numpy array

In [ ]:
np.std(my_array)

41.29837231121289

Get the biggest value in the numpy array

In [ ]:
np.max(my_array)

99

Get the smallest value in the numpy array

In [ ]:
np.min(my_array)

3

In [ ]:
print(np.sort(my_array))

[[ 3  5  8  9 88 99]
 [ 3  5  8  9 88 99]
 [ 3  5  8  9 88 99]
 [ 3  5  8  9 88 99]]
